image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - npm test
    - npm run coveralls

heroku:
  stage: deploy
  only:
    - develop
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/labour-force.git
    - git push -f heroku develop

services:
  - postgres:12.2-alpine

connect:
  image: postgres
  script:
  # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "$HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
