global:
  - CI=true
  - SECRET_KEY= secret123
  - NODE_ENV=test
  - DATABASE_URL_TEST=postgres://postgres@localhost:5432/labourforcedb_test
  - SENDGRID_API_KEY = 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
  - TEST_DB_NAME = labourforcedb_test

language: node_js
node_js:
  - 10.16.2

services:
  - postgresql

cache:
  directories:
    - "node_modules"

before_script:
  - psql -c 'CREATE DATABASE labourforcedb_test;' -U postgres
  - npm i

script:
  - npm run test
 
after_success:
  - npm run coveralls